# Generated by Django 4.2.1 on 2023-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_shoppinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ProductList',
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
