# Generated by Django 4.2.1 on 2023-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_shoppinglist_productlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='VAT_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlist',
            name='address',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlist',
            name='buyer_code',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlist',
            name='company_name',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
