# Generated by Django 4.2.1 on 2023-05-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='VAT_code',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='buyer_code',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='company_name',
        ),
    ]
