# Generated by Django 4.2.1 on 2023-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_productlist_vat_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_percentage',
            field=models.IntegerField(),
        ),
    ]
