# Generated by Django 4.2.1 on 2023-05-30 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_product_vat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '370-638-38790'", regex='^\\d{3}-\\d{3}-\\d{5}$')]),
        ),
    ]
