# Generated by Django 4.2.1 on 2023-05-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_productlist_vat_code_productlist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
