# Generated by Django 4.2.1 on 2023-05-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_product_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='summed_cost_without_vat',
        ),
    ]
