# Generated by Django 4.2.1 on 2023-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_cost_product_summed_cost_without_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
