# Generated by Django 4.2.1 on 2023-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_productlist_is_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='VAT_code',
            new_name='buyer_VAT_code',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='address',
            new_name='buyer_address',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='company_name',
            new_name='buyer_company_name',
        ),
        migrations.AddField(
            model_name='productlist',
            name='seller_VAT_code',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlist',
            name='seller_address',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlist',
            name='seller_code',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlist',
            name='seller_company_name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
