# Generated by Django 4.2.1 on 2023-05-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_usageact_productlist_usage_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usageact',
            name='product_lists',
        ),
        migrations.AlterField(
            model_name='productlist',
            name='usage_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lists', to='accounts.usageact'),
        ),
    ]
